on: workflow_dispatch

jobs:
  gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:

      - uses: actions/checkout@v4

      - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          gcloud_service_key: ${{ secrets.GCR_SERVICE_KEY }}
          registry: eu.gcr.io
          project_id: kollektivavtal
          image_name: kollektivavtal
          image_tag: latest, ${{ github.sha }}
          dockerfile: ./Dockerfile