on:
  push:
    branches:
      - main

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends
          sudo apt-get install --no-install-recommends -y openssh-client gnupg curl libjemalloc2 sqlite3 imagemagick libvips libcairo2 libcairo2-dev libgirepository1.0-dev libpoppler-glib-dev poppler-utils

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle install

      - run: bin/rubocop -f github

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}